import http from 'k6/http';
import { check, sleep } from 'k6';
import crypto from 'k6/crypto';
import encoding from 'k6/encoding';
import { createCoverage } from '/coverage.js';

// ---------------------------------------------------------------------------
// k6 load test of the BFF Calendar.
//
// Every operation of the contract (contracts/openapi.json, mounted as /openapi.json) has one
// handler below: the shared OpenAPI coverage module (mairie360/CICD tests/k6/coverage.js, see
// performance_test.sh) aborts at init when an operation has no handler, and fails the
// `operations_uncovered` threshold when a handler ends without sending its request. Adding a route
// to the BFF therefore means adding its handler here.
//
// Two scenarios share the handlers:
// - `crud` (2 VUs): `coverage.run()` calls every handler once per iteration, reads and writes, so
//   it carries the coverage gate. Handlers run path by path in contract order and, for one path,
//   in the order get, put, post, delete, options, head, patch, trace (so DELETE runs before PATCH).
//   Each iteration is one self-contained scenario: user 2 creates an event assigned to its
//   Responsable (user 3) plus a disposable one, deletes the disposable event, patches the kept one,
//   and user 3 approves it. `cleanup()` deletes the kept event at the end of the iteration.
// - `reads`: replays only the GET handlers, as random agents of init-perf.sql; they never depend on
//   `state`.
// - `events_rush`: `GET /calendar/events` at a fixed arrival rate, failing on any dropped iteration.
// Every operation gets a p(95) threshold, whose budget depends on its family (`budgetOf`).
//
// MAIR-474: the stack also runs init-perf.sql (Calendar_API's seed: 2 000 agents, 50 000 events over
// 2026-2027, 500 weekly series), every read checks that it got the agent's seeded event, and the
// thresholds are strict (every check passes, no failed request, no dropped iteration). K6_PROFILE sizes
// the load: `ci` (default) is what the 4 vCPU CI runner holds, `stress` is the high load, run by hand.
// ---------------------------------------------------------------------------

// The JWT_SECRET of the calendar-api / core-api / bff-calendar services of the test stack: random per
// run, generated by stack_secrets.sh (MAIR-474). No default: nothing is signed with a committed secret.
const JWT_SECRET = __ENV.JWT_SECRET;
if (!JWT_SECRET) throw new Error('JWT_SECRET is not set: run ./performance_test.sh, which generates it');
// User role, in group 20 with the Responsable (init-test.sql): event writes.
const USER_ID = __ENV.PERF_USER_ID || '2';
// Responsable of group 20 (init-test.sql): approves the events user 2 assigns to it.
const RESPONSABLE_ID = __ENV.PERF_RESPONSABLE_ID || '3';
// The crud scenario writes in July 2030, away from the seeded events.
const WRITE_DATE = '2030-07-01';

// Rows of init-perf.sql (Calendar_API's volume seed): agents 300001..302000; event 100000 + g
// (g = 0..49999) starts on day g % 730 of 2026-2027 and has the members 300001 + (g + 1 + 97k) % 2000,
// k = 0..2. Agent i is therefore a member of the events g = (i - 1) % 2000 + 2000m, m = 0..24.
const AGENTS = { first: 300001, count: 2000 };
const EVENTS = { first: 100000, perAgent: 25 };
const SEED_START = Date.UTC(2026, 0, 1);

const PROFILES = {
  ci: { readVus: 30, crudVus: 2, rushRate: 30 },
  stress: { readVus: 100, crudVus: 4, rushRate: 100 },
};
const PROFILE = PROFILES[__ENV.K6_PROFILE || 'ci'];
if (!PROFILE) throw new Error(`Unknown K6_PROFILE ${__ENV.K6_PROFILE}: ${Object.keys(PROFILES).join(', ')}`);

// State of the current iteration (module scope is per VU in k6).
let state = {};

function b64url(value) {
  return encoding.b64encode(value, 'rawurl');
}

// Minimal HS256 JWT accepted by Core / Calendar API (sub + role + exp claims).
function mintJwt(sub, role) {
  const header = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const now = Math.floor(Date.now() / 1000);
  const payload = b64url(JSON.stringify({ sub, role, exp: now + 3600 }));
  const signingInput = `${header}.${payload}`;
  const signature = crypto.hmac('sha256', JWT_SECRET, signingInput, 'base64rawurl');
  return `${signingInput}.${signature}`;
}

function bearer(token) {
  return { Authorization: `Bearer ${token}` };
}

const randomInt = (max) => Math.floor(Math.random() * max);
const agentTokens = {};
const pad = (n) => String(n).padStart(2, '0');

/**
 * A random seeded agent, one of the events it is a member of and the month of that event (the range the
 * front reads): the reads must find that event.
 */
function randomAgentMonth() {
  const index = randomInt(AGENTS.count);
  const id = AGENTS.first + index;
  if (!agentTokens[id]) agentTokens[id] = bearer(mintJwt(String(id), 'user'));
  const g = ((index - 1 + AGENTS.count) % AGENTS.count) + AGENTS.count * randomInt(EVENTS.perAgent);
  const day = new Date(SEED_START + (g % 730) * 86400000);
  const [year, month] = [day.getUTCFullYear(), day.getUTCMonth() + 1];
  const last = new Date(Date.UTC(year, month, 0)).getUTCDate();
  return {
    id,
    headers: agentTokens[id],
    eventId: EVENTS.first + g,
    range: { from: `${year}-${pad(month)}-01`, to: `${year}-${pad(month)}-${pad(last)}` },
  };
}

const hasEvent = (events, eventId) => Array.isArray(events) && events.some((event) => Number(event.id) === eventId);

function need(value, what) {
  if (value === undefined || value === null) {
    throw new Error(`${what} is missing, an earlier handler of this iteration failed`);
  }
  return value;
}

function json(response) {
  try {
    return response.json();
  } catch (_) {
    return null;
  }
}

function eventBody(title) {
  return {
    title,
    date: WRITE_DATE,
    startTime: '09:00',
    endTime: '10:00',
    category: 'meeting',
    service: 'direction',
    location: 'Town hall',
    assigneeIds: [`user-${RESPONSABLE_ID}`],
  };
}

const handlers = {
  // --- Connectivity (public) ---
  'GET /health': ({ request }) =>
    check(request(), { 'health 200': (r) => r.status === 200 }),
  'GET /check_apis': ({ request }) =>
    check(request(), { 'check_apis 200': (r) => r.status === 200 }),

  // --- Calendar reads ---
  // As a random seeded agent, over the month of one of its events (MAIR-474): the event must be listed.
  'GET /calendar/bootstrap': ({ request }) => {
    const agent = randomAgentMonth();
    check(request({ query: agent.range, headers: agent.headers }), {
      'bootstrap 200': (r) => r.status === 200,
      'bootstrap is the agent and lists its event': (r) =>
        r.status === 200 && (json(r) || {}).currentUser?.id === `user-${agent.id}` && hasEvent((json(r) || {}).events, agent.eventId),
    });
  },
  'GET /calendar/events': ({ request }) => {
    const agent = randomAgentMonth();
    check(request({ query: agent.range, headers: agent.headers }), {
      'events 200': (r) => r.status === 200,
      'events lists the agent event': (r) => r.status === 200 && hasEvent(json(r), agent.eventId),
    });
  },
  // The seeded agents belong to no group: they may only assign themselves.
  'GET /calendar/assignees': ({ request }) => {
    const agent = randomAgentMonth();
    check(request({ query: agent.range, headers: agent.headers }), {
      'assignees 200': (r) => r.status === 200,
      'assignees is the agent': (r) =>
        r.status === 200 && Array.isArray(json(r)) && json(r).some((assignee) => assignee.id === `user-${agent.id}`),
    });
  },
  'GET /calendar/categories': ({ request }) =>
    check(request(), { 'categories 200': (r) => r.status === 200 && Array.isArray(json(r)) && json(r).length > 0 }),
  'GET /calendar/services': ({ request }) =>
    check(request(), { 'services 200': (r) => r.status === 200 && Array.isArray(json(r)) && json(r).length > 0 }),

  // --- Event writes ---
  // Two events: one kept for PATCH and approval, one for DELETE (which runs before PATCH).
  'POST /calendar/events': ({ request }) => {
    [state.eventId, state.disposableEventId] = ['k6 event', 'k6 deleted event'].map((title) => {
      const res = request({ body: eventBody(title) });
      check(res, { 'create event 201': (r) => r.status === 201 });
      return (json(res) || {}).id;
    });
  },
  'DELETE /calendar/events/{id}': ({ request }) =>
    check(request({ path: { id: need(state.disposableEventId, 'disposable event') } }), {
      'delete event 204': (r) => r.status === 204,
    }),
  'PATCH /calendar/events/{id}': ({ request }) =>
    check(request({ path: { id: need(state.eventId, 'created event') }, body: { title: 'k6 event, patched' } }), {
      'patch event 200': (r) => r.status === 200,
    }),
  // The event was created by a User and assigned to its Responsable: it is pending until then.
  'PATCH /calendar/events/{id}/approval': ({ request, data }) =>
    check(request({ path: { id: need(state.eventId, 'created event') }, body: { approvalStatus: 'approved' }, headers: data.responsable }), {
      'approve event 200': (r) => r.status === 200 && (json(r) || {}).approvalStatus === 'approved',
    }),
};

const coverage = createCoverage(handlers);
const readOperations = coverage.operations.filter((o) => o.method === 'GET');

// Deletes the event kept by the handlers, so that the July listing does not grow during the test.
// Only its creator (user 2) may delete it.
function cleanup(data) {
  if (state.eventId === undefined || state.eventId === null) return;
  const op = 'DELETE /calendar/events/{id}';
  http.del(coverage.url(op, { id: state.eventId }), null, { headers: data.user, tags: { op } });
}

// p(95) budget of an operation, per family.
function budgetOf({ op, method }) {
  if (op === 'GET /health') return 50; // process probe
  if (op === 'GET /check_apis') return 150; // -> Calendar API /health
  if (method === 'GET') return 400; // BFF aggregation + Calendar / Core reads
  return 800; // event writes: several Calendar API calls each
}

const perOperationThresholds = {};
for (const operation of coverage.operations) {
  perOperationThresholds[`http_req_duration{op:${operation.op}}`] = [`p(95)<${budgetOf(operation)}`];
}

export const options = {
  scenarios: {
    reads: {
      executor: 'ramping-vus',
      exec: 'reads',
      stages: [
        { duration: '30s', target: Math.ceil(PROFILE.readVus / 2) }, // ramp-up
        { duration: '30s', target: PROFILE.readVus },
        { duration: '2m', target: PROFILE.readVus }, // steady load
        { duration: '20s', target: 0 }, // ramp-down
      ],
    },
    crud: {
      executor: 'constant-vus',
      exec: 'crud',
      vus: PROFILE.crudVus,
      duration: '3m20s',
    },
    // The calendar every agent opens, at a fixed arrival rate (MAIR-474): fails if k6 has to drop
    // iterations because the BFF (and Calendar API behind it) no longer keeps up.
    events_rush: {
      executor: 'constant-arrival-rate',
      exec: 'eventsRush',
      startTime: '1m', // once the reads are at their peak
      rate: PROFILE.rushRate,
      timeUnit: '1s',
      duration: '1m',
      preAllocatedVUs: 30,
      maxVUs: 200,
    },
  },
  thresholds: {
    ...coverage.thresholds,
    ...perOperationThresholds,
    'http_req_duration{op:events_rush}': ['p(95)<400'],
    dropped_iterations: ['count==0'], // the rush kept its rate
    // Strict (MAIR-474): one wrong status, one missing seeded row or one failed request fails the run.
    http_req_failed: ['rate==0'],
    checks: ['rate==1'],
  },
};

export function setup() {
  return {
    user: bearer(mintJwt(USER_ID, 'user')),
    responsable: bearer(mintJwt(RESPONSABLE_ID, 'responsable')),
  };
}

// Every GET handler, with a plain request() (no coverage accounting: `crud` owns the gate).
export function reads(data) {
  for (const operation of readOperations) {
    const request = (call = {}) =>
      http.get(coverage.url(operation.op, call.path, call.query), {
        headers: Object.assign({}, data.user, call.headers),
        tags: { op: operation.op },
      });
    handlers[operation.op]({ request, data, op: operation.op, method: operation.method, path: operation.path });
  }
  sleep(1);
}

export function eventsRush() {
  const agent = randomAgentMonth();
  const op = 'GET /calendar/events';
  check(http.get(coverage.url(op, {}, agent.range), { headers: agent.headers, tags: { op: 'events_rush' } }), {
    'rush events lists the agent event': (r) => r.status === 200 && hasEvent(json(r), agent.eventId),
  });
}

export function crud(data) {
  state = {};
  // User 2 by default; the approval handler passes the Responsable token.
  coverage.run({ headers: data.user, data });
  cleanup(data);
  sleep(1);
}
